### ISSUE TITLE
Missing instructions

### ISSUE THREAD

**Issue by RisedSky** [farisc0de/Uploady#11]
Hello, just to clarify, you can't easily install and use the readme :

```╭─ubuntu@risedsky ~/haproxy/uploady
╰─$ docker build . -t farisc0de/uploady
docker-compose up -d
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/ubuntu/haproxy/uploady/Dockerfile: no such file or directory
```

**Comment by RisedSky** [comment]
Why closing it ? Have you fixed it ?

**Comment by farisc0de** [comment]
> Why closing it ? Have you fixed it ?

Because there is no issue I tested the proposed script multiple times and on different machines and it works. just make sure that the Dockerfile is there in the folder when you execute the commands.

https://stackoverflow.com/questions/35511604/docker-unable-to-prepare-context-unable-to-evaluate-symlinks-in-dockerfile-pa
