### ISSUE TITLE
Config not writable

### ISSUE THREAD

**Issue by jxpsert** [farisc0de/Uploady#16]
Unable to proceed with installation due to ``config/config.php`` and ``config/environment.php`` not being writable. I've assigned permissions on the folders on both host machine and inside Docker, but to no avail. What could be wrong?
![image](https://github.com/farisc0de/Uploady/assets/65042215/50794d53-df71-4e90-b196-0982b1f1687f)

Here's the result of ``ls -l`` (more files above screenshot, irrelevant)
![image](https://github.com/farisc0de/Uploady/assets/65042215/52b4c479-82bd-48b0-bceb-6528b2415e84)

**Comment by dehlirious** [comment]
Well, usually you need to change the chown to www-data:www-data , not root user, it may be dependent on your install though.

Considering uploads says its writable and its also under root, it's likely with your setup thats okay.

When you did chmod, did you -r ? recursive, meaning, the config.php + environment.php inside were also changed to 777? or did you just chmod the folder, leaving the files inside not writable?

When I installed it, it said config/env wasn't writable, because they weren't. I had already typed in the user+pass and I'm lazy so I changed the permissions and then went into inspect element and removed the "disabled" on the button, clicked and it functioned+installed.

So if you really have writable permissions just do that.

**Comment by jxpsert** [comment]
Looks like it was the -R which I was missing. Thanks!

**Comment by dehlirious** [comment]
> Looks like it was the -R which I was missing. Thanks!

I'm glad it was resolvable!
